// Generated by `npx supabase gen types typescript --local --schema public`. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "app_settings": {
                  Row: {
                    "key": string,"note": string | null,"value": number
                  }
                  Insert: {
                    "key": string,"note"?: string | null,"value": number
                  }
                  Update: {
                    "key"?: string,"note"?: string | null,"value"?: number
                  }
                  Relationships: [
                    
                  ]
                },"driver_stats": {
                  Row: {
                    "driver_id": string,"first_verified_at": string | null,"last_verified_at": string | null,"updated_at": string,"verified_distance_m": number,"verified_trips": number
                  }
                  Insert: {
                    "driver_id": string,"first_verified_at"?: string | null,"last_verified_at"?: string | null,"updated_at"?: string,"verified_distance_m"?: number,"verified_trips"?: number
                  }
                  Update: {
                    "driver_id"?: string,"first_verified_at"?: string | null,"last_verified_at"?: string | null,"updated_at"?: string,"verified_distance_m"?: number,"verified_trips"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "driver_stats_driver_id_fkey"
      columns: ["driver_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"loads": {
                  Row: {
                    "created_at": string,"created_by": string | null,"drop_address": string,"drop_geog": unknown,"drop_lat": number,"drop_lng": number,"drop_radius_m": number,"id": string,"load_code": string,"material": string | null,"notes": string | null,"pickup_address": string,"pickup_geog": unknown,"pickup_lat": number,"pickup_lng": number,"pickup_radius_m": number,"planned_distance_m": number | null,"shipper_id": string | null,"weight_kg": number | null
                  }
                  Insert: {
                    "created_at"?: string,"created_by"?: string | null,"drop_address": string,"drop_geog"?: never,"drop_lat": number,"drop_lng": number,"drop_radius_m"?: number,"id"?: string,"load_code"?: string,"material"?: string | null,"notes"?: string | null,"pickup_address": string,"pickup_geog"?: never,"pickup_lat": number,"pickup_lng": number,"pickup_radius_m"?: number,"planned_distance_m"?: number | null,"shipper_id"?: string | null,"weight_kg"?: number | null
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string | null,"drop_address"?: string,"drop_geog"?: never,"drop_lat"?: number,"drop_lng"?: number,"drop_radius_m"?: number,"id"?: string,"load_code"?: string,"material"?: string | null,"notes"?: string | null,"pickup_address"?: string,"pickup_geog"?: never,"pickup_lat"?: number,"pickup_lng"?: number,"pickup_radius_m"?: number,"planned_distance_m"?: number | null,"shipper_id"?: string | null,"weight_kg"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "loads_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "loads_shipper_id_fkey"
      columns: ["shipper_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "consent_at": string | null,"consent_version": string | null,"created_at": string,"full_name": string,"id": string,"is_active": boolean,"phone": string | null,"preferred_language": string,"role": Database["public"]['Enums']["user_role"]
                  }
                  Insert: {
                    "consent_at"?: string | null,"consent_version"?: string | null,"created_at"?: string,"full_name"?: string,"id": string,"is_active"?: boolean,"phone"?: string | null,"preferred_language"?: string,"role"?: Database["public"]['Enums']["user_role"]
                  }
                  Update: {
                    "consent_at"?: string | null,"consent_version"?: string | null,"created_at"?: string,"full_name"?: string,"id"?: string,"is_active"?: boolean,"phone"?: string | null,"preferred_language"?: string,"role"?: Database["public"]['Enums']["user_role"]
                  }
                  Relationships: [
                    
                  ]
                },"trip_events": {
                  Row: {
                    "actor_id": string | null,"created_at": string,"id": number,"payload": Json | null,"trip_id": string,"type": string
                  }
                  Insert: {
                    "actor_id"?: string | null,"created_at"?: string,"id"?: never,"payload"?: Json | null,"trip_id": string,"type": string
                  }
                  Update: {
                    "actor_id"?: string | null,"created_at"?: string,"id"?: never,"payload"?: Json | null,"trip_id"?: string,"type"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "trip_events_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: false
      referencedRelation: "load_list"
      referencedColumns: ["trip_id"]
    },{
      foreignKeyName: "trip_events_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: false
      referencedRelation: "trips"
      referencedColumns: ["id"]
    }
                  ]
                },"trip_live": {
                  Row: {
                    "accuracy_m": number | null,"driver_id": string,"heading": number | null,"lat": number,"lng": number,"recorded_at": string,"speed_mps": number | null,"trip_id": string,"updated_at": string
                  }
                  Insert: {
                    "accuracy_m"?: number | null,"driver_id": string,"heading"?: number | null,"lat": number,"lng": number,"recorded_at": string,"speed_mps"?: number | null,"trip_id": string,"updated_at"?: string
                  }
                  Update: {
                    "accuracy_m"?: number | null,"driver_id"?: string,"heading"?: number | null,"lat"?: number,"lng"?: number,"recorded_at"?: string,"speed_mps"?: number | null,"trip_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "trip_live_driver_id_fkey"
      columns: ["driver_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trip_live_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: true
      referencedRelation: "load_list"
      referencedColumns: ["trip_id"]
    },{
      foreignKeyName: "trip_live_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: true
      referencedRelation: "trips"
      referencedColumns: ["id"]
    }
                  ]
                },"trip_points": {
                  Row: {
                    "accuracy_m": number | null,"altitude_m": number | null,"geog": unknown,"heading": number | null,"id": number,"is_mocked": boolean,"lat": number,"lng": number,"received_at": string,"recorded_at": string,"seq": number,"speed_mps": number | null,"trip_id": string
                  }
                  Insert: {
                    "accuracy_m"?: number | null,"altitude_m"?: number | null,"geog"?: never,"heading"?: number | null,"id"?: never,"is_mocked"?: boolean,"lat": number,"lng": number,"received_at"?: string,"recorded_at": string,"seq": number,"speed_mps"?: number | null,"trip_id": string
                  }
                  Update: {
                    "accuracy_m"?: number | null,"altitude_m"?: number | null,"geog"?: never,"heading"?: number | null,"id"?: never,"is_mocked"?: boolean,"lat"?: number,"lng"?: number,"received_at"?: string,"recorded_at"?: string,"seq"?: number,"speed_mps"?: number | null,"trip_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "trip_points_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: false
      referencedRelation: "load_list"
      referencedColumns: ["trip_id"]
    },{
      foreignKeyName: "trip_points_trip_id_fkey"
      columns: ["trip_id"]
isOneToOne: false
      referencedRelation: "trips"
      referencedColumns: ["id"]
    }
                  ]
                },"trips": {
                  Row: {
                    "created_at": string,"device_info": Json | null,"driver_id": string,"end_accuracy_m": number | null,"end_lat": number | null,"end_lng": number | null,"ended_at": string | null,"expected_points": number | null,"id": string,"load_id": string,"review_note": string | null,"reviewed_by": string | null,"start_accuracy_m": number | null,"start_lat": number | null,"start_lng": number | null,"started_at": string | null,"status": Database["public"]['Enums']["trip_status"],"tracked_distance_m": number | null,"vehicle_id": string,"verification_metrics": Json | null,"verification_reasons": (string)[],"verified_at": string | null
                  }
                  Insert: {
                    "created_at"?: string,"device_info"?: Json | null,"driver_id": string,"end_accuracy_m"?: number | null,"end_lat"?: number | null,"end_lng"?: number | null,"ended_at"?: string | null,"expected_points"?: number | null,"id"?: string,"load_id": string,"review_note"?: string | null,"reviewed_by"?: string | null,"start_accuracy_m"?: number | null,"start_lat"?: number | null,"start_lng"?: number | null,"started_at"?: string | null,"status"?: Database["public"]['Enums']["trip_status"],"tracked_distance_m"?: number | null,"vehicle_id": string,"verification_metrics"?: Json | null,"verification_reasons"?: (string)[],"verified_at"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"device_info"?: Json | null,"driver_id"?: string,"end_accuracy_m"?: number | null,"end_lat"?: number | null,"end_lng"?: number | null,"ended_at"?: string | null,"expected_points"?: number | null,"id"?: string,"load_id"?: string,"review_note"?: string | null,"reviewed_by"?: string | null,"start_accuracy_m"?: number | null,"start_lat"?: number | null,"start_lng"?: number | null,"started_at"?: string | null,"status"?: Database["public"]['Enums']["trip_status"],"tracked_distance_m"?: number | null,"vehicle_id"?: string,"verification_metrics"?: Json | null,"verification_reasons"?: (string)[],"verified_at"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "trips_driver_id_fkey"
      columns: ["driver_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trips_load_id_fkey"
      columns: ["load_id"]
isOneToOne: false
      referencedRelation: "load_list"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trips_load_id_fkey"
      columns: ["load_id"]
isOneToOne: false
      referencedRelation: "loads"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trips_reviewed_by_fkey"
      columns: ["reviewed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trips_vehicle_id_fkey"
      columns: ["vehicle_id"]
isOneToOne: false
      referencedRelation: "vehicles"
      referencedColumns: ["id"]
    }
                  ]
                },"vehicles": {
                  Row: {
                    "created_at": string,"id": string,"owner_id": string | null,"registration_no": string,"vehicle_type": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"owner_id"?: string | null,"registration_no": string,"vehicle_type": string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"owner_id"?: string | null,"registration_no"?: string,"vehicle_type"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "vehicles_owner_id_fkey"
      columns: ["owner_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            "load_list": {
                  Row: {
                    "created_at": string | null,"driver_id": string | null,"driver_name": string | null,"drop_address": string | null,"id": string | null,"load_code": string | null,"load_status": string | null,"material": string | null,"pickup_address": string | null,"planned_distance_m": number | null,"shipper_id": string | null,"trip_id": string | null,"trip_status": Database["public"]['Enums']["trip_status"] | null,"weight_kg": number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "loads_shipper_id_fkey"
      columns: ["shipper_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "trips_driver_id_fkey"
      columns: ["driver_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Functions: {
            "admin_review_trip":
{ Args: { "p_approve": boolean,"p_note": string,"p_trip_id": string }; Returns: {
              "created_at": string,
"device_info": Json | null,
"driver_id": string,
"end_accuracy_m": number | null,
"end_lat": number | null,
"end_lng": number | null,
"ended_at": string | null,
"expected_points": number | null,
"id": string,
"load_id": string,
"review_note": string | null,
"reviewed_by": string | null,
"start_accuracy_m": number | null,
"start_lat": number | null,
"start_lng": number | null,
"started_at": string | null,
"status": Database["public"]['Enums']["trip_status"],
"tracked_distance_m": number | null,
"vehicle_id": string,
"verification_metrics": Json | null,
"verification_reasons": (string)[],
"verified_at": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "trips"
        isOneToOne: true
        isSetofReturn: false
      } },
"apply_verified_stats":
{ Args: { "p_trip_id": string }; Returns: undefined
                           },
"can_read_trip":
{ Args: { "p_trip_id": string }; Returns: boolean
                           },
"end_trip":
{ Args: { "p_accuracy_m": number,"p_ended_at": string,"p_expected_points": number,"p_lat": number,"p_lng": number,"p_trip_id": string }; Returns: {
              "created_at": string,
"device_info": Json | null,
"driver_id": string,
"end_accuracy_m": number | null,
"end_lat": number | null,
"end_lng": number | null,
"ended_at": string | null,
"expected_points": number | null,
"id": string,
"load_id": string,
"review_note": string | null,
"reviewed_by": string | null,
"start_accuracy_m": number | null,
"start_lat": number | null,
"start_lng": number | null,
"started_at": string | null,
"status": Database["public"]['Enums']["trip_status"],
"tracked_distance_m": number | null,
"vehicle_id": string,
"verification_metrics": Json | null,
"verification_reasons": (string)[],
"verified_at": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "trips"
        isOneToOne: true
        isSetofReturn: false
      } },
"is_admin":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"is_load_shipper":
{ Args: { "p_load_id": string }; Returns: boolean
                           },
"is_trip_driver_for_load":
{ Args: { "p_load_id": string }; Returns: boolean
                           },
"is_trip_driver_for_vehicle":
{ Args: { "p_vehicle_id": string }; Returns: boolean
                           },
"is_vehicle_owner":
{ Args: { "p_vehicle_id": string }; Returns: boolean
                           },
"my_role":
{ Args: Record<PropertyKey, never>; Returns: Database["public"]['Enums']["user_role"]
                           },
"record_consent":
{ Args: { "p_version": string }; Returns: {
              "consent_at": string | null,
"consent_version": string | null,
"created_at": string,
"full_name": string,
"id": string,
"is_active": boolean,
"phone": string | null,
"preferred_language": string,
"role": Database["public"]['Enums']["user_role"]
            }
                          SetofOptions: {
        from: "*"
        to: "profiles"
        isOneToOne: true
        isSetofReturn: false
      } },
"set_preferred_language":
{ Args: { "p_language": string }; Returns: string
                           },
"setting":
{ Args: { "p_key": string }; Returns: number
                           },
"start_trip":
{ Args: { "p_accuracy_m": number,"p_device_info"?: Json,"p_lat": number,"p_lng": number,"p_trip_id": string }; Returns: {
              "created_at": string,
"device_info": Json | null,
"driver_id": string,
"end_accuracy_m": number | null,
"end_lat": number | null,
"end_lng": number | null,
"ended_at": string | null,
"expected_points": number | null,
"id": string,
"load_id": string,
"review_note": string | null,
"reviewed_by": string | null,
"start_accuracy_m": number | null,
"start_lat": number | null,
"start_lng": number | null,
"started_at": string | null,
"status": Database["public"]['Enums']["trip_status"],
"tracked_distance_m": number | null,
"vehicle_id": string,
"verification_metrics": Json | null,
"verification_reasons": (string)[],
"verified_at": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "trips"
        isOneToOne: true
        isSetofReturn: false
      } },
"sweep_unverified_trips":
{ Args: Record<PropertyKey, never>; Returns: undefined
                           },
"verify_trip":
{ Args: { "p_trip_id": string }; Returns: Database["public"]['Enums']["trip_status"]
                           }
          }
          Enums: {
            "trip_status": "assigned"|"in_progress"|"completed"|"verified"|"needs_review"|"rejected"|"cancelled","user_role": "driver"|"owner"|"shipper"|"admin"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "trip_status": ["assigned", "in_progress", "completed", "verified", "needs_review", "rejected", "cancelled"],"user_role": ["driver", "owner", "shipper", "admin"]
          }
        }
} as const

