import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { consoleKeys } from '@/features/console/queries';
import { isLatLng, type LatLng } from '@/lib/geo';
import { mappls } from '@/lib/mappls';
import { supabase } from '@/lib/supabase';

import {
  ilikeTerm,
  PAGE_SIZE,
  rangeStart,
  toLoadInsert,
  type AssignValues,
  type CreateLoadValues,
  type DateRange,
  type LoadStatus,
  type TripStatus,
} from './schemas';

export const loadKeys = {
  list: (f: LoadFilters) => ['loads', 'list', f] as const,
  detail: (id: string) => ['loads', 'detail', id] as const,
  trips: (f: TripFilters) => ['trips', 'list', f] as const,
  shippers: ['loads', 'shippers'] as const,
};

const pageRange = (page: number) => [page * PAGE_SIZE, page * PAGE_SIZE + PAGE_SIZE - 1] as const;

// ---------- C2 Loads (server-side filter, search, sort, pagination on the load_list view) ----------

export type LoadSort = 'created_at' | 'load_code' | 'planned_distance_m';
export interface LoadFilters {
  status: LoadStatus | 'all';
  q: string;
  range: DateRange;
  page: number;
  sort: LoadSort;
  dir: 'asc' | 'desc';
}

export function useLoadsPage(f: LoadFilters) {
  return useQuery({
    queryKey: loadKeys.list(f),
    placeholderData: keepPreviousData,
    queryFn: async () => {
      let query = supabase.from('load_list').select('*', { count: 'exact' });
      if (f.status !== 'all') query = query.eq('load_status', f.status);
      if (f.q.trim()) {
        const t = ilikeTerm(f.q);
        query = query.or(`load_code.ilike.${t},pickup_address.ilike.${t},drop_address.ilike.${t}`);
      }
      const start = rangeStart(f.range);
      if (start) query = query.gte('created_at', start);
      const [from, to] = pageRange(f.page);
      const { data, error, count } = await query
        .order(f.sort, { ascending: f.dir === 'asc', nullsFirst: false })
        .order('id')
        .range(from, to);
      if (error) throw error;
      return { rows: data, total: count ?? 0 };
    },
  });
}

// ---------- C4 Load detail ----------

export function useLoad(id: string | undefined) {
  return useQuery({
    queryKey: loadKeys.detail(id ?? ''),
    enabled: !!id,
    queryFn: async () => {
      const [load, trips] = await Promise.all([
        supabase
          .from('loads')
          .select(
            'id, load_code, pickup_address, pickup_lat, pickup_lng, pickup_radius_m, drop_address, drop_lat, drop_lng, drop_radius_m, planned_distance_m, material, weight_kg, notes, created_at, shipper:profiles!loads_shipper_id_fkey(full_name), creator:profiles!loads_created_by_fkey(full_name)',
          )
          .eq('id', id!)
          .maybeSingle(),
        supabase
          .from('trips')
          .select(
            'id, status, created_at, started_at, ended_at, tracked_distance_m, driver:profiles!trips_driver_id_fkey(id, full_name, phone), vehicle:vehicles(id, registration_no, vehicle_type)',
          )
          .eq('load_id', id!)
          .order('created_at', { ascending: false }),
      ]);
      if (load.error) throw load.error;
      if (trips.error) throw trips.error;
      return load.data ? { load: load.data, trips: trips.data } : null;
    },
  });
}

/** Statuses that keep a load's trip "open" (unique index trips_one_open_per_load). */
export const OPEN_TRIP_STATUSES: TripStatus[] = [
  'assigned',
  'in_progress',
  'completed',
  'verified',
  'needs_review',
];

// ---------- C3 Create load ----------

export function useShippers() {
  return useQuery({
    queryKey: loadKeys.shippers,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('profiles')
        .select('id, full_name')
        .eq('role', 'shipper')
        .eq('is_active', true)
        .order('full_name');
      if (error) throw error;
      return data;
    },
  });
}

export function useAutosuggest(query: string, near?: LatLng) {
  const q = query.trim();
  return useQuery({
    queryKey: ['mappls', 'autosuggest', q, near?.lat, near?.lng],
    enabled: q.length >= 3,
    staleTime: 10 * 60_000,
    retry: false,
    queryFn: () => mappls.autosuggest(q, near),
  });
}

/** Planned route line for the map (display only). */
export function usePlannedRoute(
  from: Partial<LatLng> | null | undefined,
  to: Partial<LatLng> | null | undefined,
) {
  const ok = isLatLng(from) && isLatLng(to);
  return useQuery({
    queryKey: ['mappls', 'route', from?.lat, from?.lng, to?.lat, to?.lng],
    enabled: ok,
    staleTime: Infinity,
    retry: false,
    queryFn: () => mappls.route(from as LatLng, to as LatLng),
  });
}

export class PlannedDistanceError extends Error {}

/**
 * Fetches the planned distance through mappls-proxy, then inserts the load.
 * The load code (NL-YYYY-NNNNNN) is generated by the database default.
 * `skipDistance` saves without it after the admin confirms (proxy down / no route).
 */
export function useCreateLoad() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ values, skipDistance }: { values: CreateLoadValues; skipDistance?: boolean }) => {
      let planned: number | null = null;
      if (!skipDistance) {
        try {
          planned = (await mappls.distance(values.pickup, values.drop)).distanceM;
        } catch (e) {
          throw new PlannedDistanceError(e instanceof Error ? e.message : 'distance failed');
        }
      }
      const { data, error } = await supabase
        .from('loads')
        .insert(toLoadInsert(values, planned))
        .select('id, load_code')
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ['loads', 'list'] }),
  });
}

// ---------- C4 Assign ----------

export class LoadAlreadyOpenError extends Error {}

export function useAssignTrip(loadId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (v: AssignValues) => {
      const { data, error } = await supabase
        .from('trips')
        .insert({ load_id: loadId, driver_id: v.driverId, vehicle_id: v.vehicleId })
        .select('id, status')
        .single();
      if (error?.code === '23505') throw new LoadAlreadyOpenError();
      if (error) throw error;
      return data;
    },
    onSettled: () =>
      Promise.all([
        qc.invalidateQueries({ queryKey: loadKeys.detail(loadId) }),
        qc.invalidateQueries({ queryKey: ['loads', 'list'] }),
        qc.invalidateQueries({ queryKey: ['trips', 'list'] }),
        qc.invalidateQueries({ queryKey: consoleKeys.drivers }),
        qc.invalidateQueries({ queryKey: consoleKeys.vehicles }),
      ]),
  });
}

// ---------- C5 Trips ----------

export interface TripFilters {
  statuses: TripStatus[];
  driverId: string | null;
  vehicleId: string | null;
  q: string;
  range: DateRange;
  page: number;
}

export function useTripsPage(f: TripFilters) {
  return useQuery({
    queryKey: loadKeys.trips(f),
    placeholderData: keepPreviousData,
    queryFn: async () => {
      let query = supabase
        .from('trips')
        .select(
          'id, status, created_at, started_at, ended_at, tracked_distance_m, verification_reasons, load:loads!inner(id, load_code), driver:profiles!trips_driver_id_fkey(full_name), vehicle:vehicles(registration_no)',
          { count: 'exact' },
        );
      if (f.statuses.length) query = query.in('status', f.statuses);
      if (f.driverId) query = query.eq('driver_id', f.driverId);
      if (f.vehicleId) query = query.eq('vehicle_id', f.vehicleId);
      if (f.q.trim()) query = query.ilike('load.load_code', ilikeTerm(f.q));
      const start = rangeStart(f.range);
      if (start) query = query.gte('created_at', start);
      const [from, to] = pageRange(f.page);
      const { data, error, count } = await query
        .order('created_at', { ascending: false })
        .order('id')
        .range(from, to);
      if (error) throw error;
      return { rows: data, total: count ?? 0 };
    },
  });
}
